apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      name: mongodb
  serviceName: mongodb-internal
  replicas: 3
  template:
    metadata:
      labels:
        name: mongodb
    spec:
      containers:
      - name: mongodb
        image: registry.access.redhat.com/rhscl/mongodb-34-rhel7:latest
        command:
          - run-mongod-replication
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongodb-data
          mountPath: /var/lib/mongodb/data
        readinessProbe:
          exec:
            command:
            - stat
            - /tmp/initialized
          initialDelaySeconds: 30
          timeoutSeconds: 1
        env:
        - name: MONGODB_DATABASE
          value: mongodb
        - name: MONGODB_USER
          value: mongodb_user
        - name: MONGODB_PASSWORD
          value: mongodb_password
        - name: MONGODB_ADMIN_PASSWORD
          value: mongodb_admin_password
        - name: MONGODB_REPLICA_NAME
          value: rs0
        - name: MONGODB_KEYFILE_VALUE
          value: '12345678901234567890'
        - name: MONGODB_SERVICE_NAME
          value: mongodb-internal
  volumeClaimTemplates:
  - metadata:
      name: mongodb-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: managed-nfs-storage
      resources:
        requests:
          storage: 10Gi
